development: &defaults
  app_id: 117950878254050
  client_id: b970b24f039c62ef51059ab1029d103f
  client_secret: 939b5e2ef40b1e58cad08b4416f21337
  perms: read_stream,publish_stream,offline_access,manage_pages,user_checkins,friends_checkins

test:
  <<: *defaults

production:
  <<: *defaults